services:
  - type: web
    name: accounting_system
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    envVars:
      - key: PORT
        value: 8080
    plan: free
    healthCheckPath: /api/health

databases:
  - name: license-db
    plan: free
    databaseName: license_server
