import 'package:sqlite3/sqlite3.dart';

void main() {
  final db = sqlite3.openInMemory();
  db.execute('PRAGMA foreign_keys = ON;');

  final ddl = [
    'CREATE TABLE "companies" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "fiscal_year_start" TEXT NOT NULL DEFAULT \'01-01\', "fiscal_year_end" TEXT NOT NULL DEFAULT \'12-31\', "currency" TEXT NOT NULL DEFAULT \'IQD\', "number_format" TEXT NOT NULL DEFAULT \'western\', "settings_json" TEXT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "roles" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name" TEXT NOT NULL, "permissions_json" TEXT NOT NULL DEFAULT \'{}\', "is_system" INTEGER NOT NULL DEFAULT 0, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "users" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "role_id" TEXT REFERENCES "roles" NOT NULL, "email" TEXT NOT NULL UNIQUE, "display_name" TEXT NOT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "accounts" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "code" TEXT NOT NULL, "name_ar" TEXT NOT NULL, "name_en" TEXT NULL, "type" TEXT NOT NULL, "normal_balance" TEXT NOT NULL, "parent_id" TEXT REFERENCES "accounts" NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "is_system" INTEGER NOT NULL DEFAULT 0, "linked_entity_type" TEXT NULL, "linked_entity_id" TEXT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "journal_entries" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "entry_number" INTEGER NOT NULL, "date" INTEGER NOT NULL, "description" TEXT NOT NULL, "reference" TEXT NULL, "source_type" TEXT NOT NULL, "source_id" TEXT NOT NULL, "is_reversal" INTEGER NOT NULL DEFAULT 0, "reversed_entry_id" TEXT REFERENCES "journal_entries" NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "currency_code" TEXT NOT NULL DEFAULT \'IQD\', "idempotency_key" TEXT NOT NULL UNIQUE, "created_by" TEXT REFERENCES "users" NOT NULL, "created_at" INTEGER NOT NULL, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "journal_entry_lines" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "account_id" TEXT REFERENCES "accounts" NOT NULL, "debit_amount" INTEGER NOT NULL DEFAULT 0, "credit_amount" INTEGER NOT NULL DEFAULT 0, "description" TEXT NULL, "created_at" INTEGER NOT NULL);',
    'CREATE TABLE "customers" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NULL, "address" TEXT NULL, "account_id" TEXT REFERENCES "accounts" NOT NULL, "notes" TEXT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "suppliers" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NULL, "address" TEXT NULL, "account_id" TEXT REFERENCES "accounts" NOT NULL, "notes" TEXT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "workers" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NULL, "specialty" TEXT NULL, "daily_rate" INTEGER NULL, "account_id" TEXT REFERENCES "accounts" NOT NULL, "notes" TEXT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "workshops" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name" TEXT NOT NULL, "is_own_workshop" INTEGER NOT NULL DEFAULT 1, "address" TEXT NULL, "notes" TEXT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "expense_categories" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "name_ar" TEXT NOT NULL, "name_en" TEXT NULL, "group" TEXT NOT NULL, "account_id" TEXT REFERENCES "accounts" NOT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "is_system" INTEGER NOT NULL DEFAULT 0, "sort_order" INTEGER NOT NULL DEFAULT 0, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "sales" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "customer_id" TEXT REFERENCES "customers" NULL, "sale_number" INTEGER NOT NULL, "date" INTEGER NOT NULL, "total_amount" INTEGER NOT NULL, "cash_received" INTEGER NOT NULL DEFAULT 0, "credit_amount" INTEGER NOT NULL DEFAULT 0, "payment_type" TEXT NOT NULL, "currency_code" TEXT NOT NULL DEFAULT \'IQD\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "sale_items" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "sale_id" TEXT REFERENCES "sales" NOT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unit_price" INTEGER NOT NULL, "total_price" INTEGER NOT NULL, "sort_order" INTEGER NOT NULL DEFAULT 0, "created_at" INTEGER NOT NULL);',
    'CREATE TABLE "purchases" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "supplier_id" TEXT REFERENCES "suppliers" NULL, "purchase_number" INTEGER NOT NULL, "date" INTEGER NOT NULL, "total_amount" INTEGER NOT NULL, "cash_paid" INTEGER NOT NULL DEFAULT 0, "credit_amount" INTEGER NOT NULL DEFAULT 0, "payment_type" TEXT NOT NULL, "accounting_nature" TEXT NOT NULL, "target_account_id" TEXT REFERENCES "accounts" NOT NULL, "currency_code" TEXT NOT NULL DEFAULT \'IQD\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "purchase_items" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "purchase_id" TEXT REFERENCES "purchases" NOT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unit_price" INTEGER NOT NULL, "total_price" INTEGER NOT NULL, "sort_order" INTEGER NOT NULL DEFAULT 0, "created_at" INTEGER NOT NULL);',
    'CREATE TABLE "payments" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "payment_number" INTEGER NOT NULL, "date" INTEGER NOT NULL, "amount" INTEGER NOT NULL, "payment_method" TEXT NOT NULL, "direction" TEXT NOT NULL, "customer_id" TEXT REFERENCES "customers" NULL, "supplier_id" TEXT REFERENCES "suppliers" NULL, "currency_code" TEXT NOT NULL DEFAULT \'IQD\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "payment_allocations" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "payment_id" TEXT REFERENCES "payments" NOT NULL, "sale_id" TEXT REFERENCES "sales" NULL, "purchase_id" TEXT REFERENCES "purchases" NULL, "allocated_amount" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "expenses" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "expense_number" INTEGER NOT NULL, "date" INTEGER NOT NULL, "amount" INTEGER NOT NULL, "expense_category_id" TEXT REFERENCES "expense_categories" NOT NULL, "payment_method" TEXT NOT NULL, "description" TEXT NULL, "currency_code" TEXT NOT NULL DEFAULT \'IQD\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "worker_advances" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "worker_id" TEXT REFERENCES "workers" NOT NULL, "date" INTEGER NOT NULL, "amount" INTEGER NOT NULL, "payment_method" TEXT NOT NULL DEFAULT \'cash\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "worker_salaries" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "worker_id" TEXT REFERENCES "workers" NOT NULL, "date" INTEGER NOT NULL, "gross_salary" INTEGER NOT NULL, "advance_deduction" INTEGER NOT NULL DEFAULT 0, "net_payment" INTEGER NOT NULL, "payment_method" TEXT NOT NULL DEFAULT \'cash\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "owner_withdrawals" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "date" INTEGER NOT NULL, "amount" INTEGER NOT NULL, "payment_method" TEXT NOT NULL DEFAULT \'cash\', "description" TEXT NULL, "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "manufacturing_jobs" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "job_number" INTEGER NOT NULL, "workshop_id" TEXT REFERENCES "workshops" NOT NULL, "work_type" TEXT NOT NULL, "scenario" TEXT NOT NULL, "accounting_treatment" TEXT NOT NULL, "total_cost" INTEGER NOT NULL, "date" INTEGER NOT NULL, "customer_id" TEXT REFERENCES "customers" NULL, "responsible_person" TEXT NULL, "payment_method" TEXT NOT NULL DEFAULT \'cash\', "journal_entry_id" TEXT REFERENCES "journal_entries" NOT NULL, "status" TEXT NOT NULL DEFAULT \'posted\', "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "production_records" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "worker_id" TEXT REFERENCES "workers" NOT NULL, "manufacturing_job_id" TEXT REFERENCES "manufacturing_jobs" NULL, "work_type" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "production_date" INTEGER NOT NULL, "notes" TEXT NULL, "created_by" TEXT REFERENCES "users" NOT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "is_deleted" INTEGER NOT NULL DEFAULT 0, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "audit_logs" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "user_id" TEXT REFERENCES "users" NOT NULL, "entity_type" TEXT NOT NULL, "entity_id" TEXT NOT NULL, "action" TEXT NOT NULL, "field_name" TEXT NULL, "old_value" TEXT NULL, "new_value" TEXT NULL, "timestamp" INTEGER NOT NULL, "device_id" TEXT NOT NULL, "sync_status" TEXT NOT NULL DEFAULT \'pending\');',
    'CREATE TABLE "devices" ("id" TEXT NOT NULL PRIMARY KEY, "user_id" TEXT REFERENCES "users" NOT NULL, "device_name" TEXT NOT NULL, "platform" TEXT NOT NULL, "last_seen_at" INTEGER NOT NULL, "push_token" TEXT NULL, "is_active" INTEGER NOT NULL DEFAULT 1, "created_at" INTEGER NOT NULL);',
    'CREATE TABLE "sync_outbox" ("id" TEXT NOT NULL PRIMARY KEY, "table_name" TEXT NOT NULL, "record_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "payload_json" TEXT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" INTEGER NOT NULL, "status" TEXT NOT NULL DEFAULT \'pending\', "retry_count" INTEGER NOT NULL DEFAULT 0, "last_error" TEXT NULL, "device_id" TEXT NOT NULL);',
    'CREATE TABLE "sync_metadata" ("id" TEXT NOT NULL PRIMARY KEY, "device_id" TEXT NOT NULL, "table_name" TEXT NOT NULL, "last_synced_at" INTEGER NULL, "last_sync_version" INTEGER NULL, "sync_status" TEXT NOT NULL DEFAULT \'idle\', "error_message" TEXT NULL, "created_at" INTEGER NOT NULL, "updated_at" INTEGER NOT NULL);',
    'CREATE TABLE "shared_statements" ("id" TEXT NOT NULL PRIMARY KEY, "company_id" TEXT REFERENCES "companies" NOT NULL, "entity_type" TEXT NOT NULL, "entity_id" TEXT NOT NULL, "access_token_hash" TEXT NOT NULL, "expires_at" INTEGER NOT NULL, "is_revoked" INTEGER NOT NULL DEFAULT 0, "created_by" TEXT REFERENCES "users" NOT NULL, "created_at" INTEGER NOT NULL);',
  ];

  int passed = 0;
  for (var i = 0; i < ddl.length; i++) {
    try {
      db.execute(ddl[i]);
      passed++;
    } catch (e) {
      print('Table ${i+1} FAILED: $e\nDDL: ${ddl[i]}');
    }
  }

  print('ALL 28 TABLES CREATED SUCCESSFULLY! Total passed: $passed / 28');
  db.dispose();
}
